StudentManage/application/apps/index/models.py
# coding=utf-8

from application import db


# 创建关系表,不再创建模型,一般用于表与表之间的多对多场景(3)
"""
表关系变量 = db.Table(
    "关系表表名",
    db.Column('字段名', 字段类型, 字段选项),  # 普通字段
    db.Column("字段名", 字段类型, db.ForeignKey("表名.id")),
    db.Column("字段名", 字段类型, db.ForeignKey("表名.id")),
)
"""
achievement = db.Table(
    "achievement", #表名
    db.Column('score', db.Numeric, comment="分数"), #新增字段
    db.Column('student_id', db.Integer, db.ForeignKey('student.id')),
    db.Column('course_id', db.Integer, db.ForeignKey('course.id'))
)

class Student(db.Model):
    """学生信息(1)"""
    __tablename__ = "student" #设置表名
    id = db.Column(db.Integer, primary_key=True, comment="主键ID")
    name = db.Column(db.String(64), index=True, comment="姓名" )
    sex = db.Column(db.Boolean, default=True, comment="性别")
    class_number = db.Column(db.String(32), nullable=True, index=True, comment="班级")
    age = db.Column(db.SmallInteger, comment="年龄")
    description = db.Column(db.Text, comment="个性签名")
    #创建完多对多关系表后,再创建表之间的访问关系(4)
    courses = db.relationship(
        'Course', # 模型名称
        secondary=achievement, # 表关系变量
        backref='students', # 当外键反过来获取主键信息时,使用的字段名称,可以自定义,接下来的使用例如: course.students 获取某个课程下所有的学生
        lazy='dynamic'
    )

class Course(db.Model):
    """课程信息(2)"""
    __tablename__ = "course"
    id = db.Column(db.Integer, primary_key=True,comment="主键ID")
    name = db.Column(db.String(64), unique=True,comment="课程名称")

StudentManage/application/__init__.py
#项目初始化文件
import logging
from logging.handlers import RotatingFileHandler
from flask import Flask
from redis import StrictRedis
from flask_wtf.csrf import CSRFProtect
from flask_session import Session
from flask_sqlalchemy import SQLAlchemy

from application.settings.dev import DevelopmentConfig
from application.settings.prop import ProductionConfig

config={
    'dev':DevelopmentConfig,
    'prop':ProductionConfig,

}

#增加日志模块
def setup_log(Config):
    #设置日志等级
    logging.basicConfig(level=Config.LOG_LEVEL)
    # 创建日志记录器，指明日志保存的路径、每个日志文件的最大大小、保存的日志文件个数上限
    file_log_handler=RotatingFileHandler('log/log',maxBytes=1024 * 1024 * 300, backupCount=10)
    # 创建日志记录的格式 日志等级 输入日志信息的文件名 行数 日志信息
    formatter = logging.Formatter('%(levelname)s %(filename)s:%(lineno)d %(message)s')
    # 为刚创建的日志记录器设置日志记录格式
    file_log_handler.setFormatter(formatter)
    # 为全局的日志工具对象（flaskapp使用的）添加日志记录器
    logging.getLogger().addHandler(file_log_handler)

# 为了方便redis的连接对象在函数外部可以使用,预先设置一个全局变量,接下来在函数中用于保存redis的连接

redis_store=None

#创建数据库连接对象
db=SQLAlchemy()

def init_app(config_name):
    '项目初始化'
    #主应用的根目录
    app = Flask(__name__)

    #设置配置类
    Config=config[config_name]

    #加载配置
    app.config.from_object(Config)

    #redis的连接初始化
    global redis_store
    redis_store=StrictRedis(host=Config.REDIS_HOST,port=Config.REDIS_PORT,db=0)

    #开启CSRF防范
    CSRFProtect(app)

    #开启session
    Session(app)

    #增加数据库连接
    db.init_app(app)

    #启用日志
    setup_log(Config)

    #todo 注册蓝图
    from .apps.index import index_blu
    app.register_blueprint(index_blu,url_prefix='')


    return app



StudentManage/application/apps/index/__init__.py
from flask import Blueprint

#声明蓝图
'''
template_folder:指定模板文件路径,查找顺序,先全局templates里面找,没找到,再往子蓝图里面找.

'''
#给app取别名为 'index'
index_blu=Blueprint('index',__name__,template_folder='templates',static_folder='static')

from .views import *


StudentManage/application/apps/index/views.py
#index蓝图的视图
from application import db
from application.apps.index.models import Student
from .  import index_blu
from flask import render_template, request, flash


@index_blu.route('/')
def index():
    return render_template('index.html')

@index_blu.route('/test')
def test():
    '测试静态文件'
    return render_template('test.html')


#显示学生信息
@index_blu.route('/students')
def students():
    """學生列表"""
    student_list = Student.query.all()
    data = []
    for student in student_list:
        print(student.sex)
        data.append({
            "id": student.id,
            "name": student.name,
            "age": student.age,
            "sex": "男" if student.sex else "女",
            "description": student.description,
            "class_number": student.class_number,
        })

    return render_template("students.html", students=data)


@index_blu.route("/add",methods=["POST","GET"])
def add_student():
    if request.method == "POST":
        # 接受數據
        name = request.form.get("username")
        age = int( request.form.get("age") )if request.form.get("age") else 0
        sex = True if request.form.get("sex") == '1' else False
        class_number = request.form.get("class_number")
        description = request.form.get("description")
        # 驗證數據
        if age < 0 or age > 120:
            # 閃現信息[用於返回錯誤信息給客戶端,只顯示一次]
            flash("非法的年齡數值")

        # 保存入庫
        student = Student(name=name,age=age,sex=sex,class_number=class_number,description=description)
        try:
            db.session.add(student)
            db.session.commit()
        except:
            # 事務回滾
            db.session.rollback()

    return render_template("add_students.html")

StudentManage/application/settings/__init__.py
from  redis import StrictRedis

#全局通用配置类
class Config(object):
    """项目配置核心类"""
    #调试模式
    DEBUG=True

    #todo 配置日志
    LOG_LEVEL = "DEBUG"

    #mysql数据库配置信息(指定字符集?charset=utf8)
    #数据库连接格式
    'SQLALCHEMY_DATABASE_URI ="数据库类型://用户名:密码@ip:port:库名?指定字符集编码"'
    SQLALCHEMY_DATABASE_URI = "mysql://root:123@127.0.0.1:3306/students?charset=utf8"
    # 动态追踪修改设置，如未设置只会提示警告
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    # 查询时会显示原始SQL语句
    SQLALCHEMY_ECHO = False

    # 配置redis
    # 项目上线以后，这个地址就会被替换成真实IP地址，mysql也是
    REDIS_HOST = '127.0.0.1'
    REDIS_PORT = 6379

    #设置session 秘钥
    #可以通过 base64.b64encode(os.urandom(48)) 来生成一个指定长度的随机字符串
    SECRET_KEY = "CF3tEA1J3hRyIOw3PWE3ZE9+hLOcUDq6acX/mABsEMTXNjRDm5YldRLIXazQviwP"

    #flask_session的配置信息
    SESSION_TYPE='redis' #指定session保存到redis中
    SESSION_USE_SIGNER=True # 让 cookie 中的 session_id 被加密签名处理
    SESSION_REDIS=StrictRedis(host=REDIS_HOST,port=REDIS_PORT) # 使用 redis 的实例
    PERMANENT_SESSION_LIFETIME = 24 * 60 * 60  # session 的有效期，单位是秒

StudentManage/application/apps/index/templates/add_students.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="" method="post">
    {% for message in get_flashed_messages() %}
	<span>{{message}}</span>
    {% endfor %}
    <table width="600px" align="center" border="1">
        <tr>
            <td>姓名:</td>
            <td><input type="text" name="username"></td>
        </tr>
        <tr>
            <td>年齡:</td>
            <td><input type="number" name="age"></td>
        </tr>
        <tr>
            <td>性別:</td>
            <td>
                <select name="sex">
                    <option value="1">男</option>
                    <option value="0">女</option>
                </select>
            </td>
        </tr>
        <tr>
            <td>班級:</td>
            <td><input type="text" name="class_number"></td>
        </tr>
        <tr>
            <td>個性簽名:</td>
            <td><textarea name="description"></textarea></td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td>
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <input type="submit" value="註冊">
            </td>
        </tr>
    </table>
    </form>
</body>
</html>

StudentManage/application/apps/index/templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>hello world</h1>
</body>
</html>

StudentManage/application/apps/index/templates/students.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <!--注意url_for书写格式 url_for('蓝图别名.视图函数名')-->
    <a href="{{ url_for('index.add_student') }}">新增學員</a>
    <table border="1" align="center" width="1000px">
        <tr>
            <th>ID</th>
            <th>姓名</th>
            <th>年齡</th>
            <th>性別</th>
            <th>班級</th>
            <th>個性簽名</th>
        </tr>
        {% for student in students %}
        <tr>
            <td>{{ student.id }}</td>
            <td>{{ student.name }}</td>
            <td>{{ student.age }}</td>
            <td>{{ student.sex }}</td>
            <td>{{ student.class_number }}</td>
            <td>{{ student.description }}</td>
        </tr>
        {% endfor %}

    </table>
</body>
</html>

StudentManage/application/apps/index/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>图片展示</h1>
    <p>蓝图app(index_blu)下静态文件图片</p>
    <img src="/static/ying.jpg" alt="">


    <p>全局(application)下静态文件图片</p>
    <img src="/static/yinger.jpg" alt="">


</body>
</html>